export const FETCH_ALL = "FETCH_ALL";
export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const FETCH_TRAINER = "FETCH_TRAINER";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const CREATE_TRAINER = "CREATE_TRAINER";
export const DELETE_TRAINER = "DELETE_TRAINER";
export const DELETE_POKEMON = "DELETE_POKEMON";
